import type { Config } from "../schemas/config.schema.js";
import type { Endpoint } from "../types/Endpoint.js";
import { capitalize } from "../util/capitalize.js";

export const createQueryFile = (endpoint: Endpoint, config: Config): string => {
  const { schemaPackage } = config;
  const { query, params, schemaImports, response } = endpoint;

  const content: string[] = [];

  content.push("// ------------------------------");
  content.push(`// Auto-generated query file for ${endpoint.method} ${endpoint.path}`);
  content.push("// This file is generated by Route Ink. Do not edit manually.");
  content.push("// ------------------------------");

  content.push(`import { useSuspenseQuery, UseSuspenseQueryOptions } from "@tanstack/react-query"`);
  content.push(`import axios from "axios";`);
  content.push(`import { Except } from "type-fest";`);
  content.push(`import z from "zod/v4";`);
  content.push(`import { ${schemaImports.join(", ")} } from "${schemaPackage}";`);

  const utilImports = ["buildQueryKey"];

  if (params) {
    utilImports.push("injectParams");
  }

  if (query) {
    utilImports.push("serializeSearchQuery");
  }

  const queryName = `${capitalize(endpoint.operationId)}Query`;

  content.push(`import { ${utilImports.join(", ")} } from "../util";`);
  content.push("");

  content.push(`type ${queryName}Input = {`);

  if (params) {
    content.push(`  params: z.output<typeof ${params}>;`);
  }

  if (query) {
    content.push(`  query: z.output<typeof ${query}>;`);
  }

  content.push(`};`);

  content.push("");

  return content.join("\n");
}